freebsd.rpcgen: Do terrible hack!
Current error we are hacking around:

```
rpc_scan.c: In function 'get_token':
rpc_scan.c:169:66: error: 'WUNTRACED' undeclared (first use in this function)
  169 |                                         waitpid(childpid, &stat, WUNTRACED);
      |                                                                  ^~~~~~~~~
```

I don't get this because if I go in a nix shell `WUNTRACED` is defined:

```bash
nix-shell . -A pkgsCross.x86_64-freebsd.buildPackages.freebsd.rpcgen
```

```bash
echo -e '#include <sys/wait.h>\nWUNTRACED' | $CC -E -x c - | tail
```